# Generated by Django 5.1.15 on 2026-06-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makerspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('available_quantity', models.PositiveIntegerField(default=0)),
                ('reserved_quantity', models.PositiveIntegerField(default=0)),
                ('issued_quantity', models.PositiveIntegerField(default=0)),
                ('damaged_quantity', models.PositiveIntegerField(default=0)),
                ('lost_quantity', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('show_public_count', models.BooleanField(default=False)),
                ('public_availability_mode', models.CharField(choices=[('exact_count', 'Exact Count'), ('status_only', 'Status Only'), ('hidden', 'Hidden')], default='status_only', max_length=20)),
                ('storage_location', models.CharField(blank=True, max_length=200)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('makerspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='makerspaces.makerspace')),
            ],
            options={
                'indexes': [models.Index(fields=['makerspace', 'is_public', 'is_archived'], name='inventory_i_makersp_fb8f32_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_quantity__gte', 0)), name='qty_total_nonneg'), models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0)), name='qty_available_nonneg'), models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='qty_reserved_nonneg'), models.CheckConstraint(condition=models.Q(('issued_quantity__gte', 0)), name='qty_issued_nonneg'), models.CheckConstraint(condition=models.Q(('damaged_quantity__gte', 0)), name='qty_damaged_nonneg'), models.CheckConstraint(condition=models.Q(('lost_quantity__gte', 0)), name='qty_lost_nonneg')],
            },
        ),
    ]
