# Generated by Django 5.1.15 on 2026-06-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0012_makerspace_smtp_use_ssl'),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='superadmin_access_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
