# Generated by Django 5.1.15 on 2026-06-19 05:42

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makerspaces', '0014_makerspace_archived_at_makerspace_archived_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='makerspace',
            name='frontend_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='makerspace',
            name='hidden_from_central_directory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='makerspace',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('frontend_domain'), name='uniq_makerspace_frontend_domain_ci'),
        ),
        migrations.AddConstraint(
            model_name='makerspace',
            constraint=models.CheckConstraint(condition=models.Q(('hidden_from_central_directory', False), ('frontend_domain__isnull', False), _connector='OR'), name='ck_makerspace_hidden_requires_domain'),
        ),
    ]
